// Generated by Framer (c90df04)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-vtIpwQx_u", breakpoints: [{hash: "qlf9pk", mediaQuery: "(min-width: 1200px)"}, {hash: "2a6jr5", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "pcf9h4", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-eg5ka", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=device-width"}
}

export const metadataVersion = 1