// Generated by Framer (139b156)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const QWI1IISoN = params?.QWI1IISoN
return {bodyClassName: "framer-body-l4BaYvjhl", breakpoints: [{hash: "dw24i0"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-p1I6G", title: `${QWI1IISoN !== undefined ? toString(QWI1IISoN) : "{{QWI1IISoN}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1