// Generated by Framer (0c5492c)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-PouZo .framer-styles-preset-67iwkq:not(.rich-text-wrapper), .framer-PouZo .framer-styles-preset-67iwkq.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, #f1dfc2); --framer-link-hover-text-decoration: none; --framer-link-text-color: rgba(255, 255, 255, 0.9); --framer-link-text-decoration: none; }"];
export const className = "framer-PouZo";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}