// Generated by Framer (e010222)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const FRBb8XVWk = params?.FRBb8XVWk
return {bodyClassName: "framer-body-OZ3AMGlmu", breakpoints: [{hash: "e4t3r3"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-g4hEk", title: `${FRBb8XVWk !== undefined ? toString(FRBb8XVWk) : "{{FRBb8XVWk}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1