// Generated by Framer (d65dc2b)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {FaFLCsKWf: {v0: "Housemood | Projekty", v1: "Rôznorodé projekty zaujímavého interiérového dizajnu."}}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1dsvldy", mediaQuery: "(min-width: 1200px)"}, {hash: "19auagw", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "k22g7a", mediaQuery: "(max-width: 809px)"}], description: getLocalizedValue("v1", activeLocale) ?? "A variety of cool interior design projects.", elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-jhaM2", title: getLocalizedValue("v0", activeLocale) ?? "Housemood | Projects", viewport: "width=device-width"}
}

export const metadataVersion = 1