// Generated by Framer (c563d2c)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-SL2kU .framer-styles-preset-1wcnze3:not(.rich-text-wrapper), .framer-SL2kU .framer-styles-preset-1wcnze3.rich-text-wrapper a { --framer-link-current-text-color: #111111; --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: rgba(0, 0, 0, 0.75); --framer-link-hover-text-decoration: none; --framer-link-text-color: rgba(0, 0, 0, 0.9); --framer-link-text-decoration: none; }"];
export const className = "framer-SL2kU";
export const __FramerMetadata__ = {
    "exports": {
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}