// Generated by Framer (4f3879e)
const valuesByLocaleId = {
    FaFLCsKWf: {
        v0: "Housemood | Profesion\xe1lna Agent\xfara Interi\xe9rov\xe9ho Dizajnu",
        v1: "V Housemood navrhujeme št\xfdlov\xe9, funkčn\xe9 interi\xe9ry, ktor\xe9 odr\xe1žaj\xfa vašu v\xedziu a zlepšuj\xfa v\xe1š priestor. Od domov po komerčn\xe9 projekty prin\xe1šame kreativitu a odborn\xe9 znalosti do každ\xe9ho detailu."
    }
};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        description: getLocalizedValue("v1", activeLocale) ? ? "At Housemood we design stylish, functional interiors that reflect your vision and enhance your space. From homes to commercial projects, we bring creativity and expertise to every detail.",
        favicon: "https://framerusercontent.com/assets/K7nEBxK66GMILjBvhmE9qH3Qmto.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/JZI8YzJ7valWSxaZ1UxuawgEA.png",
        title: getLocalizedValue("v0", activeLocale) ? ? "Housemood | Professional Interior Design Agency"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}