// Generated by Framer (4f3879e)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "jhtlu3", mediaQuery: "(min-width: 1200px)"}, {hash: "z8drbv", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "18d4pur", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-4NJw8", title: "Housemood | Terms", viewport: "width=device-width"}
}

export const metadataVersion = 1