// Generated by Framer (0c5492c)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/6HO9vhzkIZgHUKCiPx5H/5Kn0go3FADWD88uTrx3i/cD0evZgOT.js";
import * as sharedStyle from "https://framerusercontent.com/modules/khYtkT8dG5bFAi3Iy3tx/lwDoTT5ALFlXkB4kcXuo/xHNsUW18k.js";
const cycleOrder = ["JDLFpZHzW", "AcdRN9Ufo", "Y8rZhIPNS", "tUO9juqOC"];
const serializationHash = "framer-azOxV";
const variantClassNames = {
    AcdRN9Ufo: "framer-v-1yyb8t1",
    JDLFpZHzW: "framer-v-5fbd1p",
    tUO9juqOC: "framer-v-19rzr48",
    Y8rZhIPNS: "framer-v-7we0cu"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Small desktop": "AcdRN9Ufo",
    Desktop: "JDLFpZHzW",
    Phone: "tUO9juqOC",
    Tablet: "Y8rZhIPNS"
};
const getProps = ({
    height,
    id,
    message,
    width,
    ...props
}) => {
    return { ...props,
        cZmtJHlQz: message ? ? props.cZmtJHlQz ? ? "Message",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "JDLFpZHzW"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        cZmtJHlQz,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "JDLFpZHzW",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-5fbd1p", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "JDLFpZHzW",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: 10,
                        borderBottomRightRadius: 10,
                        borderTopLeftRadius: 10,
                        borderTopRightRadius: 10,
                        ...style
                    },
                    ...addPropertyOverrides({
                        AcdRN9Ufo: {
                            "data-framer-name": "Small desktop"
                        },
                        tUO9juqOC: {
                            "data-framer-name": "Phone"
                        },
                        Y8rZhIPNS: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant),
                    children: /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-5vtfax",
                                "data-styles-preset": "xHNsUW18k",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.5))"
                                },
                                children: "Message"
                            })
                        }),
                        className: "framer-qjksj9",
                        "data-framer-name": "The team works like storytellers, turning spaces into narratives you’ll love living in.",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "lQ1HbNi1c",
                        style: {
                            "--extracted-r6o4lv": "rgba(0, 0, 0, 0.5)",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: cZmtJHlQz,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                        ...addPropertyOverrides({
                            tUO9juqOC: {
                                children: /*#__PURE__*/ _jsx(React.Fragment, {
                                    children: /*#__PURE__*/ _jsx(motion.p, {
                                        className: "framer-styles-preset-1xoeoxz",
                                        "data-styles-preset": "cD0evZgOT",
                                        style: {
                                            "--framer-text-color": "var(--extracted-r6o4lv, rgba(0, 0, 0, 0.5))"
                                        },
                                        children: "Message"
                                    })
                                })
                            }
                        }, baseVariant, gestureVariant)
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-azOxV.framer-1gghb1v, .framer-azOxV .framer-1gghb1v { display: block; }", ".framer-azOxV.framer-5fbd1p { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 201px; justify-content: flex-end; overflow: hidden; padding: 0px 12px 12px 0px; position: relative; width: 201px; will-change: var(--framer-will-change-override, transform); }", ".framer-azOxV .framer-qjksj9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-azOxV.framer-5fbd1p { gap: 0px; } .framer-azOxV.framer-5fbd1p > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-azOxV.framer-5fbd1p > :first-child { margin-top: 0px; } .framer-azOxV.framer-5fbd1p > :last-child { margin-bottom: 0px; } }", ".framer-azOxV.framer-v-1yyb8t1.framer-5fbd1p { aspect-ratio: 1.0025252525252526 / 1; height: var(--framer-aspect-ratio-supported, 163px); width: 163px; }", ".framer-azOxV.framer-v-7we0cu.framer-5fbd1p { aspect-ratio: 1.0025252525252526 / 1; height: var(--framer-aspect-ratio-supported, 164px); width: 164px; }", ".framer-azOxV.framer-v-19rzr48.framer-5fbd1p { aspect-ratio: 1.0025252525252526 / 1; height: var(--framer-aspect-ratio-supported, 148px); width: 148px; }", ...sharedStyle.css, ...sharedStyle1.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200.5
 * @framerIntrinsicWidth 201
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"AcdRN9Ufo":{"layout":["fixed","fixed"]},"Y8rZhIPNS":{"layout":["fixed","fixed"]},"tUO9juqOC":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"cZmtJHlQz":"message"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerYlZ0SWcy0 = withCSS(Component, css, "framer-azOxV");
export default FramerYlZ0SWcy0;
FramerYlZ0SWcy0.displayName = "Message";
FramerYlZ0SWcy0.defaultProps = {
    height: 200.5,
    width: 201
};
addPropertyControls(FramerYlZ0SWcy0, {
    variant: {
        options: ["JDLFpZHzW", "AcdRN9Ufo", "Y8rZhIPNS", "tUO9juqOC"],
        optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    cZmtJHlQz: {
        defaultValue: "Message",
        description: "Write your text",
        displayTextArea: false,
        title: "Message",
        type: ControlType.String
    }
});
addFonts(FramerYlZ0SWcy0, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerYlZ0SWcy0",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"AcdRN9Ufo\":{\"layout\":[\"fixed\",\"fixed\"]},\"Y8rZhIPNS\":{\"layout\":[\"fixed\",\"fixed\"]},\"tUO9juqOC\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "200.5",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "201",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"cZmtJHlQz\":\"message\"}"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./YlZ0SWcy0.map