// Generated by Framer (d65dc2b)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {FaFLCsKWf: {v0: ({ FRBb8XVWk }) => `${FRBb8XVWk !== undefined ? toString(FRBb8XVWk) : "{{FRBb8XVWk}}"} - Domáca nálada`, v1: "Elegantný a moderný interiérový dizajn."}}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const FRBb8XVWk = params?.FRBb8XVWk
return {breakpoints: [{hash: "rvc674", mediaQuery: "(min-width: 1200px)"}, {hash: "1ki34p7", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "17yv9ui", mediaQuery: "(max-width: 809px)"}], description: getLocalizedValue("v1", activeLocale) ?? "Sleek and modern interior design.", elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-XASuv", title: getLocalizedValue("v0", activeLocale)?.({ FRBb8XVWk }) ?? `${FRBb8XVWk !== undefined ? toString(FRBb8XVWk) : "{{FRBb8XVWk}}"} - Housemood`, viewport: "width=device-width"}
}

export const metadataVersion = 1