// Generated by Framer (ab6b6d5)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-S0Tfc9izn", breakpoints: [{hash: "1mcix6o"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-0aRhj", title: siteMetadata(params, activeLocale).title || "Page", viewport: "width=1200"}
}

export const metadataVersion = 1