// Generated by Framer (4f3879e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    Container,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX,
    withOptimizedAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import AllMainMenu from "#framer/local/canvasComponent/aKg3Cntwq/aKg3Cntwq.js";
import Footer from "#framer/local/canvasComponent/PNAqjQxer/PNAqjQxer.js";
import getLocalizedValue, {
    usePreloadLocalizedValues
} from "#framer/local/localization/B5PIsci0C/B5PIsci0C.js";
const AllMainMenuFonts = getFonts(AllMainMenu);
const MotionDivWithOptimizedAppearEffect = withOptimizedAppearEffect(motion.div);
const FooterFonts = getFonts(Footer);
const ContainerWithFX = withFX(Container);
const breakpoints = {
    PCrflUNy8: "(min-width: 810px) and (max-width: 1199px)",
    T7WagMobC: "(min-width: 1200px)",
    vLrqsugtf: "(max-width: 809px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-vh7pw";
const variantClassNames = {
    PCrflUNy8: "framer-v-1fmsygi",
    T7WagMobC: "framer-v-npo9zj",
    vLrqsugtf: "framer-v-14sk282"
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const transition1 = {
    bounce: .1,
    delay: 0,
    duration: 1.9,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: .001,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -40
};
const breakpointRules = {
    vLrqsugtf: [".framer-vh7pw .framer-if3ww7 { bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 20px); left: 20px; min-width: 145px; right: unset; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    vLrqsugtf: ".framer-14sk282-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-vh7pw.framer-ximobp, .framer-vh7pw .framer-ximobp { display: block; }", ".framer-vh7pw.framer-npo9zj { align-content: center; align-items: center; background-color: var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, #f1f1f1); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-vh7pw .framer-1lvmzts { align-content: center; align-items: center; background-color: var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 0px; width: 100%; will-change: var(--framer-will-change-effect-override, transform); z-index: 3; }", ".framer-vh7pw .framer-fe399p-container { flex: none; height: auto; position: relative; width: 100%; z-index: 4; }", ".framer-vh7pw .framer-13a7ai { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-vh7pw .framer-1lduwei-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }", ".framer-vh7pw .framer-if3ww7 { align-content: center; align-items: center; bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 65px); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 40px; min-width: 144px; order: 1003; overflow: hidden; padding: 0px; position: var(--framer-canvas-fixed-position, fixed); right: 20px; width: min-content; z-index: 10; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    PCrflUNy8: "(min-width: 810px) and (max-width: 1199px)",
    T7WagMobC: "(min-width: 1200px)",
    vLrqsugtf: "(max-width: 809px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "T7WagMobC",
    Phone: "vLrqsugtf",
    Tablet: "PCrflUNy8"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "T7WagMobC"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    usePreloadLocalizedValues(activeLocale);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "T7WagMobC",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-npo9zj", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(MotionDivWithOptimizedAppearEffect, {
                    animate: animation,
                    className: "framer-1lvmzts",
                    "data-framer-appear-id": "1lvmzts",
                    "data-framer-layout-hint-center-x": true,
                    "data-framer-name": "menucontainer",
                    initial: animation1,
                    optimized: true,
                    transformTemplate: transformTemplate1,
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 130,
                        width: "100vw",
                        y: 0,
                        children: /*#__PURE__*/ _jsx(Container, {
                            className: "framer-fe399p-container",
                            nodeId: "bXvAMCdGd",
                            scopeId: "B5PIsci0C",
                            children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                    PCrflUNy8: {
                                        variant: "iUYxFgW8Y"
                                    },
                                    vLrqsugtf: {
                                        variant: "LmJb_01N1"
                                    }
                                },
                                children: /*#__PURE__*/ _jsx(AllMainMenu, {
                                    asP_7haI7: "https://x.com/_mayweather",
                                    BtD60YMbI: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                    CEUijCSEA: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                    EpoQmTR0P: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                    Gf8wrDG77: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                    height: "100%",
                                    id: "bXvAMCdGd",
                                    ii9Mr66q4: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                    layoutId: "bXvAMCdGd",
                                    olhT3Zqp4: "mailto:hi@housemood.com",
                                    PaGpdN0xF: "tel:+38(099)791-00-75",
                                    rg_1nJnLs: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                    SM5MNNElk: "https://www.instagram.com/timofeybak/",
                                    style: {
                                        width: "100%"
                                    },
                                    TfzmL5AtK: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                    ucPLAor7a: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                    V8I1Crr1F: "https://www.behance.net/_Inee_",
                                    variant: "rrafaB8TE",
                                    width: "100%"
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-13a7ai"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 826,
                    width: "100vw",
                    y: 1e3,
                    children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                        __framer__styleTransformEffectEnabled: true,
                        __framer__transformTargets: [{
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: -480
                            }
                        }, {
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 0
                            }
                        }],
                        __framer__transformTrigger: "onInView",
                        __perspectiveFX: false,
                        __targetOpacity: 1,
                        className: "framer-1lduwei-container",
                        nodeId: "hGs3gkrDj",
                        rendersWithMotion: true,
                        scopeId: "B5PIsci0C",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                PCrflUNy8: {
                                    variant: "Oa12AhY64"
                                },
                                vLrqsugtf: {
                                    variant: "fz6dkj9bA"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                aKU8FfuzO: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                AwWcM_sWc: "https://www.instagram.com/timofeybak/",
                                B2l0cS28h: "mailto: hi@housemood.com",
                                c2bxBwHxB: "https://x.com/_mayweather",
                                c62qCzbcf: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                E7catcfem: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                height: "100%",
                                id: "hGs3gkrDj",
                                IwCoZJHF3: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                layoutId: "hGs3gkrDj",
                                LmOZ20cgt: "https://www.behance.net/_Inee_",
                                m5f2yJuM0: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                oXchGUJQR: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                qZvfcA_ha: "tel: +38(099)791-00-75",
                                style: {
                                    width: "100%"
                                },
                                sUajyPELY: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                US5FHS_MG: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                variant: "RH4AblKzf",
                                width: "100%"
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx("div", {
                    className: "framer-if3ww7",
                    "data-framer-name": "Remove Me (Remix Button)"
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1607
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"PCrflUNy8":{"layout":["fixed","fixed"]},"vLrqsugtf":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"T7WagMobC":[".framer-1lvmzts",".framer-1lduwei-container",".framer-if3ww7"],"PCrflUNy8":[".framer-1lvmzts",".framer-1lduwei-container",".framer-if3ww7"],"vLrqsugtf":[".framer-1lvmzts",".framer-1lduwei-container",".framer-if3ww7"]}
 * @framerBreakpoints {"T7WagMobC":{"min":1200,"canvasClassName":"framer-npo9zj-override","minHeight":1607,"name":"Desktop","width":1200,"rootFontSize":16},"PCrflUNy8":{"min":810,"max":1199,"canvasClassName":"framer-1fmsygi-override","minHeight":1607,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"vLrqsugtf":{"max":809,"canvasClassName":"framer-14sk282-override","minHeight":1607,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant T7WagMobC
 * @framerLayoutTemplate
 */
const FramerB5PIsci0C = withCSS(Component, css, "framer-vh7pw");
export default FramerB5PIsci0C;
FramerB5PIsci0C.displayName = "Project";
FramerB5PIsci0C.defaultProps = {
    height: 1607,
    width: 1200
};
addFonts(FramerB5PIsci0C, [{
    explicitInter: true,
    fonts: []
}, ...AllMainMenuFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerB5PIsci0C",
            "slots": [],
            "annotations": {
                "framerDefaultVariant": "T7WagMobC",
                "framerLayoutTemplate": "",
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerBreakpoints": "{\"T7WagMobC\":{\"min\":1200,\"canvasClassName\":\"framer-npo9zj-override\",\"minHeight\":1607,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"PCrflUNy8\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-1fmsygi-override\",\"minHeight\":1607,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"vLrqsugtf\":{\"max\":809,\"canvasClassName\":\"framer-14sk282-override\",\"minHeight\":1607,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerHitTargets": "{\"T7WagMobC\":[\".framer-1lvmzts\",\".framer-1lduwei-container\",\".framer-if3ww7\"],\"PCrflUNy8\":[\".framer-1lvmzts\",\".framer-1lduwei-container\",\".framer-if3ww7\"],\"vLrqsugtf\":[\".framer-1lvmzts\",\".framer-1lduwei-container\",\".framer-if3ww7\"]}",
                "framerImmutableVariables": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"PCrflUNy8\":{\"layout\":[\"fixed\",\"fixed\"]},\"vLrqsugtf\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "1200",
                "framerAutoSizeImages": "true",
                "framerIntrinsicHeight": "1607"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}