// Generated by Framer (4f3879e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    Container,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX,
    withOptimizedAppearEffect
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import AllMainMenu from "#framer/local/canvasComponent/aKg3Cntwq/aKg3Cntwq.js";
import Footer from "#framer/local/canvasComponent/PNAqjQxer/PNAqjQxer.js";
import getLocalizedValue, {
    usePreloadLocalizedValues
} from "#framer/local/localization/LNnnv1t65/LNnnv1t65.js";
const AllMainMenuFonts = getFonts(AllMainMenu);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const FooterFonts = getFonts(Footer);
const ContainerWithFX = withFX(Container);
const breakpoints = {
    D1kMBjR5V: "(min-width: 810px) and (max-width: 1199px)",
    jMAOY4bzR: "(max-width: 809px)",
    WaGiAskYu: "(min-width: 1200px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-BIIP1";
const variantClassNames = {
    D1kMBjR5V: "framer-v-ipf4be",
    jMAOY4bzR: "framer-v-1yicgug",
    WaGiAskYu: "framer-v-1arnfpt"
};
const transition1 = {
    bounce: .1,
    delay: 3,
    duration: 1.9,
    type: "spring"
};
const animation = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const animation1 = {
    opacity: .001,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: -40
};
const breakpointRules = {
    D1kMBjR5V: [".framer-BIIP1 .framer-125xon { min-width: 144px; width: min-content; }"],
    jMAOY4bzR: [".framer-BIIP1 .framer-117602m { flex-direction: column; }", ".framer-BIIP1 .framer-10efnul-container { flex: none; width: 100%; }", ".framer-BIIP1 .framer-125xon { bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 63px); min-width: 144px; right: 18px; width: min-content; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    D1kMBjR5V: ".framer-ipf4be-override",
    jMAOY4bzR: ".framer-1yicgug-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-BIIP1.framer-1hjdyl2, .framer-BIIP1 .framer-1hjdyl2 { display: block; }", ".framer-BIIP1.framer-1arnfpt { align-content: center; align-items: center; background-color: #ffffff; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-BIIP1 .framer-117602m { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; left: 50%; overflow: visible; padding: 0px; position: absolute; top: 0px; transform: translateX(-50%); width: 100%; z-index: 4; }", ".framer-BIIP1 .framer-10efnul-container { flex: 1 0 0px; height: auto; pointer-events: auto; position: relative; width: 1px; will-change: var(--framer-will-change-effect-override, transform); z-index: 4; }", ".framer-BIIP1 .framer-1w2zsdk { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-BIIP1 .framer-1w3oe2a-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }", ".framer-BIIP1 .framer-125xon { align-content: center; align-items: center; bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 65px); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 40px; order: 1003; overflow: hidden; padding: 0px; position: var(--framer-canvas-fixed-position, fixed); right: 20px; width: 144px; z-index: 10; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    D1kMBjR5V: "(min-width: 810px) and (max-width: 1199px)",
    jMAOY4bzR: "(max-width: 809px)",
    WaGiAskYu: "(min-width: 1200px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "WaGiAskYu",
    Phone: "jMAOY4bzR",
    Tablet: "D1kMBjR5V"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "WaGiAskYu"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    usePreloadLocalizedValues(activeLocale);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "WaGiAskYu",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: rgb(255, 255, 255); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-1arnfpt", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx("div", {
                    className: "framer-117602m",
                    "data-framer-layout-hint-center-x": true,
                    "data-framer-name": "menucontainer",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                            jMAOY4bzR: {
                                width: "100vw"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 130,
                            width: "max(100vw, 1px)",
                            y: 0,
                            children: /*#__PURE__*/ _jsx(ContainerWithOptimizedAppearEffect, {
                                animate: animation,
                                className: "framer-10efnul-container",
                                "data-framer-appear-id": "10efnul",
                                initial: animation1,
                                nodeId: "ltPhFrCZE",
                                optimized: true,
                                rendersWithMotion: true,
                                scopeId: "LNnnv1t65",
                                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                        D1kMBjR5V: {
                                            variant: "KAdTlFsJP"
                                        },
                                        jMAOY4bzR: {
                                            variant: "lOW5eNWpi"
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsx(AllMainMenu, {
                                        asP_7haI7: "https://x.com/_mayweather",
                                        BtD60YMbI: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                        CEUijCSEA: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                        EpoQmTR0P: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                        Gf8wrDG77: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                        height: "100%",
                                        id: "ltPhFrCZE",
                                        ii9Mr66q4: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                        layoutId: "ltPhFrCZE",
                                        olhT3Zqp4: "mailto: hi@housemood.com",
                                        PaGpdN0xF: "tel: +38(099)791-00-75",
                                        rg_1nJnLs: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                        SM5MNNElk: "https://www.instagram.com/timofeybak/",
                                        style: {
                                            width: "100%"
                                        },
                                        TfzmL5AtK: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                        ucPLAor7a: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                        V8I1Crr1F: "https://www.behance.net/_Inee_",
                                        variant: "q99BQvyno",
                                        width: "100%"
                                    })
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1w2zsdk"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 826,
                    width: "100vw",
                    y: 1e3,
                    children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                        __framer__styleTransformEffectEnabled: true,
                        __framer__transformTargets: [{
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: -480
                            }
                        }, {
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 0
                            }
                        }],
                        __framer__transformTrigger: "onInView",
                        __perspectiveFX: false,
                        __targetOpacity: 1,
                        className: "framer-1w3oe2a-container",
                        nodeId: "mDhigmMVI",
                        rendersWithMotion: true,
                        scopeId: "LNnnv1t65",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                D1kMBjR5V: {
                                    variant: "Oa12AhY64"
                                },
                                jMAOY4bzR: {
                                    variant: "fz6dkj9bA"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                aKU8FfuzO: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                AwWcM_sWc: "https://www.instagram.com/timofeybak/",
                                B2l0cS28h: "mailto: hi@housemood.com",
                                c2bxBwHxB: "https://x.com/_mayweather",
                                c62qCzbcf: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                E7catcfem: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                height: "100%",
                                id: "mDhigmMVI",
                                IwCoZJHF3: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                layoutId: "mDhigmMVI",
                                LmOZ20cgt: "https://www.behance.net/_Inee_",
                                m5f2yJuM0: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                oXchGUJQR: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                qZvfcA_ha: "tel: +38(099)791-00-75",
                                style: {
                                    width: "100%"
                                },
                                sUajyPELY: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                US5FHS_MG: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                variant: "RH4AblKzf",
                                width: "100%"
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx("div", {
                    className: "framer-125xon",
                    "data-framer-name": "Remove Me (Remix Button)"
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1556
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"D1kMBjR5V":{"layout":["fixed","fixed"]},"jMAOY4bzR":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"WaGiAskYu":[".framer-117602m",".framer-1w3oe2a-container",".framer-125xon"],"D1kMBjR5V":[".framer-117602m",".framer-1w3oe2a-container",".framer-125xon"],"jMAOY4bzR":[".framer-117602m",".framer-1w3oe2a-container",".framer-125xon"]}
 * @framerBreakpoints {"WaGiAskYu":{"min":1200,"canvasClassName":"framer-1arnfpt-override","minHeight":1556,"viewportHeight":762,"name":"Desktop","width":1200,"rootFontSize":16},"D1kMBjR5V":{"min":810,"max":1199,"canvasClassName":"framer-ipf4be-override","minHeight":1556,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"jMAOY4bzR":{"max":809,"canvasClassName":"framer-1yicgug-override","minHeight":1556,"viewportHeight":844,"name":"Phone","width":468,"rootFontSize":16}}
 * @framerDefaultVariant WaGiAskYu
 * @framerLayoutTemplate
 */
const FramerLNnnv1t65 = withCSS(Component, css, "framer-BIIP1");
export default FramerLNnnv1t65;
FramerLNnnv1t65.displayName = "Main";
FramerLNnnv1t65.defaultProps = {
    height: 1556,
    width: 1200
};
addFonts(FramerLNnnv1t65, [{
    explicitInter: true,
    fonts: []
}, ...AllMainMenuFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerLNnnv1t65",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerIntrinsicWidth": "1200",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"D1kMBjR5V\":{\"layout\":[\"fixed\",\"fixed\"]},\"jMAOY4bzR\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerAutoSizeImages": "true",
                "framerBreakpoints": "{\"WaGiAskYu\":{\"min\":1200,\"canvasClassName\":\"framer-1arnfpt-override\",\"minHeight\":1556,\"viewportHeight\":762,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"D1kMBjR5V\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-ipf4be-override\",\"minHeight\":1556,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"jMAOY4bzR\":{\"max\":809,\"canvasClassName\":\"framer-1yicgug-override\",\"minHeight\":1556,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":468,\"rootFontSize\":16}}",
                "framerDisplayContentsDiv": "false",
                "framerColorSyntax": "true",
                "framerLayoutTemplate": "",
                "framerHitTargets": "{\"WaGiAskYu\":[\".framer-117602m\",\".framer-1w3oe2a-container\",\".framer-125xon\"],\"D1kMBjR5V\":[\".framer-117602m\",\".framer-1w3oe2a-container\",\".framer-125xon\"],\"jMAOY4bzR\":[\".framer-117602m\",\".framer-1w3oe2a-container\",\".framer-125xon\"]}",
                "framerIntrinsicHeight": "1556",
                "framerContractVersion": "1",
                "framerDefaultVariant": "WaGiAskYu",
                "framerImmutableVariables": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}