// Generated by Framer (c563d2c)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const cycleOrder = ["AemDr3mcU", "KL665sTgB", "Yzcww_SqP", "lXwC1b3ZG"];
const serializationHash = "framer-Uef59";
const variantClassNames = {
    AemDr3mcU: "framer-v-12kt906",
    KL665sTgB: "framer-v-1ybtd9c",
    lXwC1b3ZG: "framer-v-xgfrla",
    Yzcww_SqP: "framer-v-ii77h9"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const toResponsiveImage = value => {
    if (typeof value === "object" && value !== null && typeof value.src === "string") {
        return value;
    }
    return typeof value === "string" ? {
        src: value
    } : undefined;
};
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    "Small desktop": "KL665sTgB",
    Desktop: "AemDr3mcU",
    Phone: "lXwC1b3ZG",
    Tablet: "Yzcww_SqP"
};
const getProps = ({
    height,
    id,
    image,
    width,
    ...props
}) => {
    return { ...props,
        doDK0MdAy: image ? ? props.doDK0MdAy,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "AemDr3mcU"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        doDK0MdAy,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "AemDr3mcU",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "",
                        fit: "fill",
                        loading: getLoadingLazyAtYPosition(componentViewport ? .y || 0),
                        sizes: componentViewport ? .width || "100vw",
                        ...toResponsiveImage(doDK0MdAy)
                    },
                    className: cx(scopingClassNames, "framer-12kt906", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "AemDr3mcU",
                    ref: ref ? ? ref1,
                    style: {
                        borderBottomLeftRadius: 10,
                        borderBottomRightRadius: 10,
                        borderTopLeftRadius: 10,
                        borderTopRightRadius: 10,
                        ...style
                    },
                    ...addPropertyOverrides({
                        KL665sTgB: {
                            "data-framer-name": "Small desktop"
                        },
                        lXwC1b3ZG: {
                            "data-framer-name": "Phone"
                        },
                        Yzcww_SqP: {
                            "data-framer-name": "Tablet"
                        }
                    }, baseVariant, gestureVariant)
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Uef59.framer-11nbo7e, .framer-Uef59 .framer-11nbo7e { display: block; }", ".framer-Uef59.framer-12kt906 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 201px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 432px; will-change: var(--framer-will-change-override, transform); }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Uef59.framer-12kt906 { gap: 0px; } .framer-Uef59.framer-12kt906 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Uef59.framer-12kt906 > :first-child { margin-top: 0px; } .framer-Uef59.framer-12kt906 > :last-child { margin-bottom: 0px; } }", ".framer-Uef59.framer-v-1ybtd9c.framer-12kt906 { aspect-ratio: 2.154040404040404 / 1; height: var(--framer-aspect-ratio-supported, 166px); width: 356px; }", ".framer-Uef59.framer-v-ii77h9.framer-12kt906 { aspect-ratio: 2.154040404040404 / 1; height: var(--framer-aspect-ratio-supported, 166px); width: 358px; }", ".framer-Uef59.framer-v-xgfrla.framer-12kt906 { height: 151px; width: 326px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200.5
 * @framerIntrinsicWidth 432
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"KL665sTgB":{"layout":["fixed","fixed"]},"Yzcww_SqP":{"layout":["fixed","fixed"]},"lXwC1b3ZG":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"doDK0MdAy":"image"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerzoM_e2RL8 = withCSS(Component, css, "framer-Uef59");
export default FramerzoM_e2RL8;
FramerzoM_e2RL8.displayName = "Moment long";
FramerzoM_e2RL8.defaultProps = {
    height: 200.5,
    width: 432
};
addPropertyControls(FramerzoM_e2RL8, {
    variant: {
        options: ["AemDr3mcU", "KL665sTgB", "Yzcww_SqP", "lXwC1b3ZG"],
        optionTitles: ["Desktop", "Small desktop", "Tablet", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    doDK0MdAy: {
        description: "Change the image",
        title: "Image",
        type: ControlType.ResponsiveImage
    }
});
addFonts(FramerzoM_e2RL8, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerzoM_e2RL8",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerVariables": "{\"doDK0MdAy\":\"image\"}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"KL665sTgB\":{\"layout\":[\"fixed\",\"fixed\"]},\"Yzcww_SqP\":{\"layout\":[\"fixed\",\"fixed\"]},\"lXwC1b3ZG\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "432",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "200.5",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./zoM_e2RL8.map