// Generated by Framer (c90df04)

import siteMetadata from "../siteMetadata/siteMetadata";

const toString = (value) => {
    return typeof value === "string" ? value : String(value);
};


export default function metadata(params, activeLocale) {
const FRBb8XVWk = params?.FRBb8XVWk
return {bodyClassName: "framer-body-G6EvqLuXC", breakpoints: [{hash: "1jfa8xh"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-aV4Yn", title: `${FRBb8XVWk !== undefined ? toString(FRBb8XVWk) : "{{FRBb8XVWk}}"} - My Framer Site`, viewport: "width=1200"}
}

export const metadataVersion = 1