// Generated by Framer (4f3879e)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    ComponentViewportProvider,
    Container,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    withCSS,
    withFX
} from "framer";
import {
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import AllMainMenu from "#framer/local/canvasComponent/aKg3Cntwq/aKg3Cntwq.js";
import Footer from "#framer/local/canvasComponent/PNAqjQxer/PNAqjQxer.js";
import getLocalizedValue, {
    usePreloadLocalizedValues
} from "#framer/local/localization/o7MhpsHA0/o7MhpsHA0.js";
const AllMainMenuFonts = getFonts(AllMainMenu);
const FooterFonts = getFonts(Footer);
const ContainerWithFX = withFX(Container);
const breakpoints = {
    IkuV5UtX7: "(min-width: 810px) and (max-width: 1199px)",
    IYHe7uLLA: "(max-width: 809px)",
    YO31Rm3bc: "(min-width: 1200px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-LMk49";
const variantClassNames = {
    IkuV5UtX7: "framer-v-1mvp4li",
    IYHe7uLLA: "framer-v-uu1f4",
    YO31Rm3bc: "framer-v-1svjv56"
};
const breakpointRules = {
    IYHe7uLLA: [".framer-LMk49 .framer-19xshqo { flex-direction: column; }", ".framer-LMk49 .framer-6nxq3-container { flex: none; width: 100%; }", ".framer-LMk49 .framer-1t9cx98 { bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 20px); left: 20px; min-width: 145px; right: unset; }"]
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    IYHe7uLLA: ".framer-uu1f4-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-LMk49.framer-16ldman, .framer-LMk49 .framer-16ldman { display: block; }", ".framer-LMk49.framer-1svjv56 { align-content: center; align-items: center; background-color: var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, #f1f1f1); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }", ".framer-LMk49 .framer-19xshqo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 0px; position: absolute; top: 0px; transform: translateX(-50%); width: 100%; z-index: 10; }", ".framer-LMk49 .framer-6nxq3-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; z-index: 4; }", ".framer-LMk49 .framer-1cwma9s { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }", ".framer-LMk49 .framer-1rs5hzl-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }", ".framer-LMk49 .framer-1t9cx98 { align-content: center; align-items: center; bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 65px); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; min-height: 40px; min-width: 144px; order: 1003; overflow: hidden; padding: 0px; position: var(--framer-canvas-fixed-position, fixed); right: 20px; width: min-content; z-index: 10; }", '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }'];
const mediaQueries = {
    IkuV5UtX7: "(min-width: 810px) and (max-width: 1199px)",
    IYHe7uLLA: "(max-width: 809px)",
    YO31Rm3bc: "(min-width: 1200px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "YO31Rm3bc",
    Phone: "IYHe7uLLA",
    Tablet: "IkuV5UtX7"
};
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "YO31Rm3bc"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    usePreloadLocalizedValues(activeLocale);
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "YO31Rm3bc",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-d2b066e4-862e-404f-95b2-5699d2c66515, rgb(241, 241, 241)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-1svjv56", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx("div", {
                    className: "framer-19xshqo",
                    "data-framer-layout-hint-center-x": true,
                    "data-framer-name": "menucontainer",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                            IYHe7uLLA: {
                                width: "100vw"
                            }
                        },
                        children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 130,
                            width: "max(100vw, 1px)",
                            y: 0,
                            children: /*#__PURE__*/ _jsx(Container, {
                                className: "framer-6nxq3-container",
                                nodeId: "d7zP5hElH",
                                scopeId: "o7MhpsHA0",
                                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                        IkuV5UtX7: {
                                            variant: "iUYxFgW8Y"
                                        },
                                        IYHe7uLLA: {
                                            variant: "LmJb_01N1"
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsx(AllMainMenu, {
                                        asP_7haI7: "https://x.com/_mayweather",
                                        BtD60YMbI: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                        CEUijCSEA: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                        EpoQmTR0P: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                        Gf8wrDG77: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                        height: "100%",
                                        id: "d7zP5hElH",
                                        ii9Mr66q4: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                        layoutId: "d7zP5hElH",
                                        olhT3Zqp4: "mailto:hi@housemood.com",
                                        PaGpdN0xF: "tel:+38(099)791-00-75",
                                        rg_1nJnLs: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                        SM5MNNElk: "https://www.instagram.com/timofeybak/",
                                        style: {
                                            width: "100%"
                                        },
                                        TfzmL5AtK: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                        ucPLAor7a: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                        V8I1Crr1F: "https://www.behance.net/_Inee_",
                                        variant: "rrafaB8TE",
                                        width: "100%"
                                    })
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1cwma9s"
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 826,
                    width: "100vw",
                    y: 1e3,
                    children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                        __framer__styleTransformEffectEnabled: true,
                        __framer__transformTargets: [{
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: -480
                            }
                        }, {
                            target: {
                                opacity: 1,
                                rotate: 0,
                                rotateX: 0,
                                rotateY: 0,
                                scale: 1,
                                skewX: 0,
                                skewY: 0,
                                x: 0,
                                y: 0
                            }
                        }],
                        __framer__transformTrigger: "onInView",
                        __perspectiveFX: false,
                        __targetOpacity: 1,
                        className: "framer-1rs5hzl-container",
                        nodeId: "aVhI29PN0",
                        rendersWithMotion: true,
                        scopeId: "o7MhpsHA0",
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                IkuV5UtX7: {
                                    variant: "Oa12AhY64"
                                },
                                IYHe7uLLA: {
                                    variant: "fz6dkj9bA"
                                }
                            },
                            children: /*#__PURE__*/ _jsx(Footer, {
                                aKU8FfuzO: getLocalizedValue("v2", activeLocale) ? ? "App. 390",
                                AwWcM_sWc: "https://www.instagram.com/timofeybak/",
                                B2l0cS28h: "mailto: hi@housemood.com",
                                c2bxBwHxB: "https://x.com/_mayweather",
                                c62qCzbcf: getLocalizedValue("v7", activeLocale) ? ? "Twitter",
                                E7catcfem: getLocalizedValue("v3", activeLocale) ? ? "hi@housemood.com",
                                height: "100%",
                                id: "aVhI29PN0",
                                IwCoZJHF3: getLocalizedValue("v4", activeLocale) ? ? "(099) 791-00-75",
                                layoutId: "aVhI29PN0",
                                LmOZ20cgt: "https://www.behance.net/_Inee_",
                                m5f2yJuM0: getLocalizedValue("v1", activeLocale) ? ? "Str. Believein Yourself 29",
                                oXchGUJQR: getLocalizedValue("v0", activeLocale) ? ? "France, Paris",
                                qZvfcA_ha: "tel: +38(099)791-00-75",
                                style: {
                                    width: "100%"
                                },
                                sUajyPELY: getLocalizedValue("v5", activeLocale) ? ? "Instagram",
                                US5FHS_MG: getLocalizedValue("v6", activeLocale) ? ? "Behance",
                                variant: "RH4AblKzf",
                                width: "100%"
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx("div", {
                    className: "framer-1t9cx98",
                    "data-framer-name": "Remove Me (Remix Button)"
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1604
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"IkuV5UtX7":{"layout":["fixed","fixed"]},"IYHe7uLLA":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"YO31Rm3bc":[".framer-19xshqo",".framer-1rs5hzl-container",".framer-1t9cx98"],"IkuV5UtX7":[".framer-19xshqo",".framer-1rs5hzl-container",".framer-1t9cx98"],"IYHe7uLLA":[".framer-19xshqo",".framer-1rs5hzl-container",".framer-1t9cx98"]}
 * @framerBreakpoints {"YO31Rm3bc":{"min":1200,"canvasClassName":"framer-1svjv56-override","minHeight":1604,"name":"Desktop","width":1200,"rootFontSize":16},"IkuV5UtX7":{"min":810,"max":1199,"canvasClassName":"framer-1mvp4li-override","minHeight":1604,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"IYHe7uLLA":{"max":809,"canvasClassName":"framer-uu1f4-override","minHeight":1604,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant YO31Rm3bc
 * @framerLayoutTemplate
 */
const Framero7MhpsHA0 = withCSS(Component, css, "framer-LMk49");
export default Framero7MhpsHA0;
Framero7MhpsHA0.displayName = "All Inners";
Framero7MhpsHA0.defaultProps = {
    height: 1604,
    width: 1200
};
addFonts(Framero7MhpsHA0, [{
    explicitInter: true,
    fonts: []
}, ...AllMainMenuFonts, ...FooterFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "Framero7MhpsHA0",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "1604",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicWidth": "1200",
                "framerDisplayContentsDiv": "false",
                "framerDefaultVariant": "YO31Rm3bc",
                "framerImmutableVariables": "true",
                "framerLayoutTemplate": "",
                "framerBreakpoints": "{\"YO31Rm3bc\":{\"min\":1200,\"canvasClassName\":\"framer-1svjv56-override\",\"minHeight\":1604,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"IkuV5UtX7\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-1mvp4li-override\",\"minHeight\":1604,\"viewportHeight\":1080,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"IYHe7uLLA\":{\"max\":809,\"canvasClassName\":\"framer-uu1f4-override\",\"minHeight\":1604,\"viewportHeight\":844,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"IkuV5UtX7\":{\"layout\":[\"fixed\",\"fixed\"]},\"IYHe7uLLA\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerAutoSizeImages": "true",
                "framerHitTargets": "{\"YO31Rm3bc\":[\".framer-19xshqo\",\".framer-1rs5hzl-container\",\".framer-1t9cx98\"],\"IkuV5UtX7\":[\".framer-19xshqo\",\".framer-1rs5hzl-container\",\".framer-1t9cx98\"],\"IYHe7uLLA\":[\".framer-19xshqo\",\".framer-1rs5hzl-container\",\".framer-1t9cx98\"]}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}