// Generated by Framer (6aa4fc0)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1hey3g1", mediaQuery: "(min-width: 1440px)"}, {hash: "1sxtdoa", mediaQuery: "(min-width: 810px) and (max-width: 1439px)"}, {hash: "d1j01h", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: false}, robots: "noindex", serializationId: "framer-lXrFc", title: "Housemood | 404", viewport: "width=device-width"}
}

export const metadataVersion = 1