// Generated by Framer (0c5492c)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    SmartComponentScopedContainer,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import Ticker from "https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/jyRNgY7vYWXe6t31T0wo/Ticker.js";
import TickerItem from "https://framerusercontent.com/modules/YSGEr0BUj8We2vlvY2We/gbCzjBOdIJtj2LAHWjsb/lNORRWB3c.js";
const TickerItemFonts = getFonts(TickerItem);
const TickerFonts = getFonts(Ticker);
const cycleOrder = ["R2Do3WnrT", "YDhdkOjhW"];
const serializationHash = "framer-CFmUr";
const variantClassNames = {
    R2Do3WnrT: "framer-v-4qtfq2",
    YDhdkOjhW: "framer-v-gfk449"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const isSet = value => {
    if (Array.isArray(value)) return value.length > 0;
    return value !== undefined && value !== null && value !== "";
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "R2Do3WnrT",
    Phone: "YDhdkOjhW"
};
const getProps = ({
    descript1St,
    descript2Nd,
    descript3Rd,
    descript4Th,
    descript5Th,
    height,
    id,
    number1St,
    number2Nd,
    number3Rd,
    number4Th,
    number5Th,
    speed,
    width,
    ...props
}) => {
    return { ...props,
        eBqMtzQHE: number1St ? ? props.eBqMtzQHE ? ? "0%",
        kpxbnMuh9: number3Rd ? ? props.kpxbnMuh9 ? ? "0%",
        mWirz3oxs: number2Nd ? ? props.mWirz3oxs ? ? "0%",
        ocoluOEZo: speed ? ? props.ocoluOEZo ? ? 40,
        QLdX1zqoU: descript5Th ? ? props.QLdX1zqoU ? ? "Descript 5th",
        tinhmYfS8: descript3Rd ? ? props.tinhmYfS8 ? ? "Descript 3rd",
        U7MJejad2: descript2Nd ? ? props.U7MJejad2 ? ? "Descript 2nd",
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "R2Do3WnrT",
        WFUNR5_Ok: descript1St ? ? props.WFUNR5_Ok ? ? "Descript 1st",
        WuukyzOlW: descript4Th ? ? props.WuukyzOlW ? ? "Descript 4th",
        wZIgtp_0x: number4Th ? ? props.wZIgtp_0x ? ? "0%",
        ZCe3Bjl8W: number5Th ? ? props.ZCe3Bjl8W ? ? "0%"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        ocoluOEZo,
        eBqMtzQHE,
        WFUNR5_Ok,
        mWirz3oxs,
        U7MJejad2,
        kpxbnMuh9,
        tinhmYfS8,
        wZIgtp_0x,
        WuukyzOlW,
        ZCe3Bjl8W,
        QLdX1zqoU,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "R2Do3WnrT",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = () => {
        if (baseVariant === "YDhdkOjhW") return true;
        return false;
    };
    const visible = isSet(QLdX1zqoU);
    const visible1 = isSet(WuukyzOlW);
    const visible2 = isSet(tinhmYfS8);
    const visible3 = isSet(U7MJejad2);
    const visible4 = isSet(WFUNR5_Ok);
    const isDisplayed1 = () => {
        if (baseVariant === "YDhdkOjhW") return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-4qtfq2", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "R2Do3WnrT",
                    ref: refBinding,
                    style: {
                        backgroundColor: "var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194))",
                        ...style
                    },
                    ...addPropertyOverrides({
                        YDhdkOjhW: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [isDisplayed() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-5kbhzj-container",
                            "data-framer-name": "Ticker mobile",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "ckvZq6Qta-container",
                            name: "Ticker mobile",
                            nodeId: "ckvZq6Qta",
                            rendersWithMotion: true,
                            scopeId: "B9jM9frcv",
                            children: /*#__PURE__*/ _jsx(Ticker, {
                                alignment: "center",
                                direction: "left",
                                fadeOptions: {
                                    fadeAlpha: 0,
                                    fadeContent: false,
                                    fadeInset: 0,
                                    fadeWidth: 25,
                                    overflow: false
                                },
                                gap: 24,
                                height: "100%",
                                hoverFactor: 1,
                                id: "ckvZq6Qta",
                                layoutId: "ckvZq6Qta",
                                name: "Ticker mobile",
                                padding: 0,
                                paddingBottom: 0,
                                paddingLeft: 0,
                                paddingPerSide: false,
                                paddingRight: 0,
                                paddingTop: 0,
                                sizingOptions: {
                                    heightType: true,
                                    widthType: false
                                },
                                slots: [visible && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "224px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-14zm63z-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "P8pZesjmC-container",
                                        nodeId: "P8pZesjmC",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "P8pZesjmC",
                                            layoutId: "P8pZesjmC",
                                            variant: "KLsRrsbDa",
                                            width: "100%",
                                            ZIr9YwD4h: QLdX1zqoU,
                                            ZNZ57xlX4: ZCe3Bjl8W
                                        })
                                    })
                                }), visible1 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "225px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-w96z1r-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "yggz4JM5v-container",
                                        nodeId: "yggz4JM5v",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "yggz4JM5v",
                                            layoutId: "yggz4JM5v",
                                            variant: "KLsRrsbDa",
                                            width: "100%",
                                            ZIr9YwD4h: WuukyzOlW,
                                            ZNZ57xlX4: wZIgtp_0x
                                        })
                                    })
                                }), visible2 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "225.5px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1dd55e6-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "QaakDO6Ik-container",
                                        nodeId: "QaakDO6Ik",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "QaakDO6Ik",
                                            layoutId: "QaakDO6Ik",
                                            variant: "KLsRrsbDa",
                                            width: "100%",
                                            ZIr9YwD4h: tinhmYfS8,
                                            ZNZ57xlX4: kpxbnMuh9
                                        })
                                    })
                                }), visible3 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "231px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-8ztiq-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "WaMBCoWoY-container",
                                        nodeId: "WaMBCoWoY",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "WaMBCoWoY",
                                            layoutId: "WaMBCoWoY",
                                            variant: "KLsRrsbDa",
                                            width: "100%",
                                            ZIr9YwD4h: U7MJejad2,
                                            ZNZ57xlX4: mWirz3oxs
                                        })
                                    })
                                }), visible4 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "217.5px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-7itjzn-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "ZNrPiyON6-container",
                                        nodeId: "ZNrPiyON6",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "ZNrPiyON6",
                                            layoutId: "ZNrPiyON6",
                                            variant: "KLsRrsbDa",
                                            width: "100%",
                                            ZIr9YwD4h: WFUNR5_Ok,
                                            ZNZ57xlX4: eBqMtzQHE
                                        })
                                    })
                                })],
                                speed: ocoluOEZo,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    }), isDisplayed1() && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1f4via0-container",
                            isAuthoredByUser: true,
                            isModuleExternal: true,
                            layoutDependency: layoutDependency,
                            layoutId: "MpyBAEvlE-container",
                            nodeId: "MpyBAEvlE",
                            rendersWithMotion: true,
                            scopeId: "B9jM9frcv",
                            children: /*#__PURE__*/ _jsx(Ticker, {
                                alignment: "center",
                                direction: "left",
                                fadeOptions: {
                                    fadeAlpha: 0,
                                    fadeContent: false,
                                    fadeInset: 0,
                                    fadeWidth: 52,
                                    overflow: false
                                },
                                gap: 52,
                                height: "100%",
                                hoverFactor: 1,
                                id: "MpyBAEvlE",
                                layoutId: "MpyBAEvlE",
                                padding: 0,
                                paddingBottom: 0,
                                paddingLeft: 0,
                                paddingPerSide: false,
                                paddingRight: 0,
                                paddingTop: 0,
                                sizingOptions: {
                                    heightType: true,
                                    widthType: false
                                },
                                slots: [visible && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "269.5px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1u2oi9y-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "bgl09ogfl-container",
                                        nodeId: "bgl09ogfl",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "bgl09ogfl",
                                            layoutId: "bgl09ogfl",
                                            variant: "ffxAIvklm",
                                            width: "100%",
                                            ZIr9YwD4h: QLdX1zqoU,
                                            ZNZ57xlX4: ZCe3Bjl8W
                                        })
                                    })
                                }), visible1 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "270.5px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1ylw3au-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "EH9Q1HN1E-container",
                                        nodeId: "EH9Q1HN1E",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "EH9Q1HN1E",
                                            layoutId: "EH9Q1HN1E",
                                            variant: "ffxAIvklm",
                                            width: "100%",
                                            ZIr9YwD4h: WuukyzOlW,
                                            ZNZ57xlX4: wZIgtp_0x
                                        })
                                    })
                                }), visible2 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "271px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-khzlcb-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "bFxTYcRS4-container",
                                        nodeId: "bFxTYcRS4",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "bFxTYcRS4",
                                            layoutId: "bFxTYcRS4",
                                            variant: "ffxAIvklm",
                                            width: "100%",
                                            ZIr9YwD4h: tinhmYfS8,
                                            ZNZ57xlX4: kpxbnMuh9
                                        })
                                    })
                                }), visible3 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "277px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-oslgvq-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "SDf9qUd_B-container",
                                        nodeId: "SDf9qUd_B",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "SDf9qUd_B",
                                            layoutId: "SDf9qUd_B",
                                            variant: "ffxAIvklm",
                                            width: "100%",
                                            ZIr9YwD4h: U7MJejad2,
                                            ZNZ57xlX4: mWirz3oxs
                                        })
                                    })
                                }), visible4 && /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                    height: 46,
                                    width: "262.5px",
                                    children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                        className: "framer-1brccfa-container",
                                        inComponentSlot: true,
                                        layoutDependency: layoutDependency,
                                        layoutId: "HIIm9QxzI-container",
                                        nodeId: "HIIm9QxzI",
                                        rendersWithMotion: true,
                                        scopeId: "B9jM9frcv",
                                        children: /*#__PURE__*/ _jsx(TickerItem, {
                                            height: "100%",
                                            id: "HIIm9QxzI",
                                            layoutId: "HIIm9QxzI",
                                            variant: "ffxAIvklm",
                                            width: "100%",
                                            ZIr9YwD4h: WFUNR5_Ok,
                                            ZNZ57xlX4: eBqMtzQHE
                                        })
                                    })
                                })],
                                speed: ocoluOEZo,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-CFmUr.framer-r0swye, .framer-CFmUr .framer-r0swye { display: block; }", ".framer-CFmUr.framer-4qtfq2 { height: 84px; overflow: hidden; position: relative; width: 1400px; }", ".framer-CFmUr .framer-5kbhzj-container, .framer-CFmUr .framer-1f4via0-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }", ".framer-CFmUr .framer-14zm63z-container, .framer-CFmUr .framer-w96z1r-container, .framer-CFmUr .framer-1dd55e6-container, .framer-CFmUr .framer-8ztiq-container, .framer-CFmUr .framer-7itjzn-container, .framer-CFmUr .framer-1u2oi9y-container, .framer-CFmUr .framer-1ylw3au-container, .framer-CFmUr .framer-khzlcb-container, .framer-CFmUr .framer-oslgvq-container, .framer-CFmUr .framer-1brccfa-container { height: auto; position: relative; width: auto; }", ".framer-CFmUr.framer-v-gfk449.framer-4qtfq2 { height: 70px; width: 390px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 84
 * @framerIntrinsicWidth 1400
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"YDhdkOjhW":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"ocoluOEZo":"speed","eBqMtzQHE":"number1St","WFUNR5_Ok":"descript1St","mWirz3oxs":"number2Nd","U7MJejad2":"descript2Nd","kpxbnMuh9":"number3Rd","tinhmYfS8":"descript3Rd","wZIgtp_0x":"number4Th","WuukyzOlW":"descript4Th","ZCe3Bjl8W":"number5Th","QLdX1zqoU":"descript5Th"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerB9jM9frcv = withCSS(Component, css, "framer-CFmUr");
export default FramerB9jM9frcv;
FramerB9jM9frcv.displayName = "Ticker";
FramerB9jM9frcv.defaultProps = {
    height: 84,
    width: 1400
};
addPropertyControls(FramerB9jM9frcv, {
    variant: {
        options: ["R2Do3WnrT", "YDhdkOjhW"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    ocoluOEZo: {
        defaultValue: 40,
        displayStepper: true,
        max: 1e3,
        min: 0,
        step: 5,
        title: "Speed",
        type: ControlType.Number
    },
    eBqMtzQHE: {
        defaultValue: "0%",
        displayTextArea: false,
        placeholder: "",
        title: "Number 1st",
        type: ControlType.String
    },
    WFUNR5_Ok: {
        defaultValue: "Descript 1st",
        displayTextArea: false,
        title: "Descript 1st",
        type: ControlType.String
    },
    mWirz3oxs: {
        defaultValue: "0%",
        displayTextArea: false,
        placeholder: "",
        title: "Number 2nd",
        type: ControlType.String
    },
    U7MJejad2: {
        defaultValue: "Descript 2nd",
        displayTextArea: false,
        title: "Descript 2nd",
        type: ControlType.String
    },
    kpxbnMuh9: {
        defaultValue: "0%",
        displayTextArea: false,
        placeholder: "",
        title: "Number 3rd",
        type: ControlType.String
    },
    tinhmYfS8: {
        defaultValue: "Descript 3rd",
        displayTextArea: false,
        title: "Descript 3rd",
        type: ControlType.String
    },
    wZIgtp_0x: {
        defaultValue: "0%",
        displayTextArea: false,
        placeholder: "",
        title: "Number 4th",
        type: ControlType.String
    },
    WuukyzOlW: {
        defaultValue: "Descript 4th",
        displayTextArea: false,
        title: "Descript 4th",
        type: ControlType.String
    },
    ZCe3Bjl8W: {
        defaultValue: "0%",
        displayTextArea: false,
        placeholder: "",
        title: "Number 5th",
        type: ControlType.String
    },
    QLdX1zqoU: {
        defaultValue: "Descript 5th",
        displayTextArea: false,
        title: "Descript 5th",
        type: ControlType.String
    }
});
addFonts(FramerB9jM9frcv, [{
    explicitInter: true,
    fonts: []
}, ...TickerItemFonts, ...TickerFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FramerB9jM9frcv",
            "slots": [],
            "annotations": {
                "framerIntrinsicHeight": "84",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"YDhdkOjhW\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerVariables": "{\"ocoluOEZo\":\"speed\",\"eBqMtzQHE\":\"number1St\",\"WFUNR5_Ok\":\"descript1St\",\"mWirz3oxs\":\"number2Nd\",\"U7MJejad2\":\"descript2Nd\",\"kpxbnMuh9\":\"number3Rd\",\"tinhmYfS8\":\"descript3Rd\",\"wZIgtp_0x\":\"number4Th\",\"WuukyzOlW\":\"descript4Th\",\"ZCe3Bjl8W\":\"number5Th\",\"QLdX1zqoU\":\"descript5Th\"}",
                "framerDisplayContentsDiv": "false",
                "framerAutoSizeImages": "true",
                "framerImmutableVariables": "true",
                "framerContractVersion": "1",
                "framerIntrinsicWidth": "1400",
                "framerComponentViewportWidth": "true",
                "framerColorSyntax": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./B9jM9frcv.map