// Generated by Framer (d65dc2b)
import siteMetadata from "https://framerusercontent.com/modules/vTJfokjN5kwKjpgcX1mV/pDsBnu1bGfU18dlm6tFo/siteMetadata.js";
const valuesByLocaleId = {};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        breakpoints: [{
            hash: "72rtr7",
            mediaQuery: "(min-width: 1200px)"
        }, {
            hash: "1lg1qtq",
            mediaQuery: "(min-width: 810px) and (max-width: 1199px)"
        }, {
            hash: "2wk8na",
            mediaQuery: "(max-width: 809px)"
        }],
        description: siteMetadata(params, activeLocale).description,
        elements: {},
        framerSearch: {
            index: true
        },
        robots: "max-image-preview:large",
        serializationId: "framer-nAlDF",
        title: siteMetadata(params, activeLocale).title || "Home",
        viewport: "width=device-width"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}