// Generated by Framer (0c5492c)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/kLCpcPbtcedywgjN6bFY/LljUicHp1fzjZapvwbtl/hbmF94ei7.js";
const serializationHash = "framer-7s30D";
const variantClassNames = {
    NI1W8I2f5: "framer-v-12u7er1"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const isSet = value => {
    if (Array.isArray(value)) return value.length > 0;
    return value !== undefined && value !== null && value !== "";
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    item1St,
    item2Nd,
    item3Rd,
    item4Th,
    width,
    ...props
}) => {
    return { ...props,
        C3ak6BQZE: item3Rd ? ? props.C3ak6BQZE ? ? "3D visualisation",
        d5BPDz7w6: item2Nd ? ? props.d5BPDz7w6 ? ? "Design Project",
        DR68LWtHN: item4Th ? ? props.DR68LWtHN ? ? "Supervision",
        tGnLuBZNd: item1St ? ? props.tGnLuBZNd ? ? "Tech Specifications"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        tGnLuBZNd,
        d5BPDz7w6,
        C3ak6BQZE,
        DR68LWtHN,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "NI1W8I2f5",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const visible = isSet(tGnLuBZNd);
    const visible1 = isSet(d5BPDz7w6);
    const visible2 = isSet(C3ak6BQZE);
    const visible3 = isSet(DR68LWtHN);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-12u7er1", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "NI1W8I2f5",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [visible && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-ku03k4",
                                "data-styles-preset": "hbmF94ei7",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))"
                                },
                                children: "Tech Specifications"
                            })
                        }),
                        className: "framer-18fg9ll",
                        "data-framer-name": "Tech Specifications",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "mNTIMa1OY",
                        style: {
                            "--extracted-r6o4lv": "var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: tGnLuBZNd,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), visible1 && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-ku03k4",
                                "data-styles-preset": "hbmF94ei7",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))"
                                },
                                children: "Design Project"
                            })
                        }),
                        className: "framer-8dmlg0",
                        "data-framer-name": "Design Project",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "n6A1t8LSK",
                        style: {
                            "--extracted-r6o4lv": "var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: d5BPDz7w6,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), visible2 && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-ku03k4",
                                "data-styles-preset": "hbmF94ei7",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))"
                                },
                                children: "3D visualisation"
                            })
                        }),
                        className: "framer-17e2u3o",
                        "data-framer-name": "3D visualisation",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "wPHzWiKeR",
                        style: {
                            "--extracted-r6o4lv": "var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: C3ak6BQZE,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), visible3 && /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-ku03k4",
                                "data-styles-preset": "hbmF94ei7",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))"
                                },
                                children: "Supervision"
                            })
                        }),
                        className: "framer-4gr3l6",
                        "data-framer-name": "Supervision",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "YHUbaae_6",
                        style: {
                            "--extracted-r6o4lv": "var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: DR68LWtHN,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-7s30D.framer-17u8lzw, .framer-7s30D .framer-17u8lzw { display: block; }", ".framer-7s30D.framer-12u7er1 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 317px; }", ".framer-7s30D .framer-18fg9ll, .framer-7s30D .framer-8dmlg0, .framer-7s30D .framer-17e2u3o, .framer-7s30D .framer-4gr3l6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-7s30D.framer-12u7er1 { gap: 0px; } .framer-7s30D.framer-12u7er1 > * { margin: 0px; margin-bottom: calc(5px / 2); margin-top: calc(5px / 2); } .framer-7s30D.framer-12u7er1 > :first-child { margin-top: 0px; } .framer-7s30D.framer-12u7er1 > :last-child { margin-bottom: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 103
 * @framerIntrinsicWidth 316.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"tGnLuBZNd":"item1St","d5BPDz7w6":"item2Nd","C3ak6BQZE":"item3Rd","DR68LWtHN":"item4Th"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameriJSefLji4 = withCSS(Component, css, "framer-7s30D");
export default FrameriJSefLji4;
FrameriJSefLji4.displayName = "Hero items";
FrameriJSefLji4.defaultProps = {
    height: 103,
    width: 316.5
};
addPropertyControls(FrameriJSefLji4, {
    tGnLuBZNd: {
        defaultValue: "Tech Specifications",
        displayTextArea: false,
        title: "Item 1st",
        type: ControlType.String
    },
    d5BPDz7w6: {
        defaultValue: "Design Project",
        displayTextArea: false,
        title: "Item 2nd",
        type: ControlType.String
    },
    C3ak6BQZE: {
        defaultValue: "3D visualisation",
        displayTextArea: false,
        title: "Item 3rd",
        type: ControlType.String
    },
    DR68LWtHN: {
        defaultValue: "Supervision",
        description: "Write your items",
        displayTextArea: false,
        title: "Item 4th",
        type: ControlType.String
    }
});
addFonts(FrameriJSefLji4, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FrameriJSefLji4",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicWidth": "316.5",
                "framerAutoSizeImages": "true",
                "framerVariables": "{\"tGnLuBZNd\":\"item1St\",\"d5BPDz7w6\":\"item2Nd\",\"C3ak6BQZE\":\"item3Rd\",\"DR68LWtHN\":\"item4Th\"}",
                "framerIntrinsicHeight": "103",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./iJSefLji4.map