// Generated by Framer (f082bd6)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "2vkxm2"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-EBhxT", title: siteMetadata(params, activeLocale).title || "Privacy", viewport: "width=1200"}
}

export const metadataVersion = 1