// Generated by Framer (4f3879e)
import {
    addPropertyControls as e,
    ControlType as t,
    QueryCache as l,
    QueryEngine as i
} from "framer";
import {
    DatabaseCollection as r
} from "./gFwBjMfM0-0.js";
import {
    resolveRichText as a
} from "./gFwBjMfM0-1.js";
import {
    resolveRichTextSk as n
} from "./gFwBjMfM0-3.js";
let o = {
        id: {
            isNullable: !1,
            type: t.String
        },
        nextItemId: {
            isNullable: !0,
            type: t.String
        },
        NkZkE4Nmw: {
            isNullable: !0,
            type: t.String
        },
        previousItemId: {
            isNullable: !0,
            type: t.String
        },
        QWI1IISoN: {
            isNullable: !0,
            type: t.String
        }
    },
    m = [],
    u = e => {
        let t = m[e];
        if (t) return t().then(e => e.default);
    },
    p = new i,
    f = new l(p),
    c = {
        collectionByLocaleId: {
            default: new r({
                chunks: [new URL("./gFwBjMfM0-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [],
                resolveRichText: a,
                resolveVectorSetItem: u,
                schema: o
            }),
            FaFLCsKWf: new r({
                chunks: [new URL("./gFwBjMfM0-chunk-FaFLCsKWf-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [],
                resolveRichText: n,
                resolveVectorSetItem: u,
                schema: o
            })
        },
        displayName: "Categories"
    };
export default c;
e(c, {
    QWI1IISoN: {
        defaultValue: "",
        title: "Title",
        type: t.String
    },
    NkZkE4Nmw: {
        title: "Slug",
        type: t.String
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/gFwBjMfM0:default",
        title: "Previous",
        type: t.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/gFwBjMfM0:default",
        title: "Next",
        type: t.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, t) {
        let [l] = await f.get({
            from: {
                data: c,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "NkZkE4Nmw",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .NkZkE4Nmw;
    },
    async getRecordIdBySlug(e, t) {
        let [l] = await f.get({
            from: {
                data: c,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "NkZkE4Nmw",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, t).readAsync();
        return l ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerSlug": "NkZkE4Nmw",
                "framerColorSyntax": "false",
                "framerCollectionUtils": "1",
                "framerRecordIdKey": "id",
                "framerData": "",
                "framerContractVersion": "1",
                "framerEnumToDisplayNameUtils": "2",
                "framerCollectionId": "gFwBjMfM0"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}