// Generated by Framer (0c5492c)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    getFontsFromSharedStyle,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/RQyCV46a8g5rP6u5mKKD/qhiZWeFlKrHbQtRBunvR/CJkhvaLRU.js";
const serializationHash = "framer-j1Xqa";
const variantClassNames = {
    j6YVZYzTZ: "framer-v-82is4l"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    partBottom,
    partTop,
    width,
    ...props
}) => {
    return { ...props,
        aglOvVM2H: partBottom ? ? props.aglOvVM2H ? ? "Part bottom",
        iG0Gm77Mi: partTop ? ? props.iG0Gm77Mi ? ? "Part top"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        iG0Gm77Mi,
        aglOvVM2H,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "j6YVZYzTZ",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const sharedStyleClassNames = [sharedStyle.className];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-82is4l", className, classNames),
                    "data-framer-name": "Variant 1",
                    layoutDependency: layoutDependency,
                    layoutId: "j6YVZYzTZ",
                    ref: refBinding,
                    style: { ...style
                    },
                    children: [ /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-w9yjg9",
                                "data-styles-preset": "CJkhvaLRU",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255)))"
                                },
                                children: "Part1"
                            })
                        }),
                        className: "framer-k9yr39",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "HtLhvTHYM",
                        style: {
                            "--extracted-r6o4lv": "var(--token-3142cc16-0cd9-425a-970e-aecfb62e7f87, rgb(255, 255, 255))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: iG0Gm77Mi,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    }), /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                                className: "framer-styles-preset-w9yjg9",
                                "data-styles-preset": "CJkhvaLRU",
                                style: {
                                    "--framer-text-color": "var(--extracted-r6o4lv, var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194)))"
                                },
                                children: "Part2"
                            })
                        }),
                        className: "framer-qfeomt",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "XTXUqQhyt",
                        style: {
                            "--extracted-r6o4lv": "var(--token-801a1a18-ec2a-44b0-b58c-7538b430c2c1, rgb(241, 223, 194))",
                            "--framer-paragraph-spacing": "0px"
                        },
                        text: aglOvVM2H,
                        verticalAlignment: "top",
                        withExternalLayout: true
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-j1Xqa.framer-1l5p0yx, .framer-j1Xqa .framer-1l5p0yx { display: block; }", ".framer-j1Xqa.framer-82is4l { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 317px; }", ".framer-j1Xqa .framer-k9yr39, .framer-j1Xqa .framer-qfeomt { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-j1Xqa.framer-82is4l { gap: 0px; } .framer-j1Xqa.framer-82is4l > * { margin: 0px; margin-bottom: calc(2px / 2); margin-top: calc(2px / 2); } .framer-j1Xqa.framer-82is4l > :first-child { margin-top: 0px; } .framer-j1Xqa.framer-82is4l > :last-child { margin-bottom: 0px; } }", ...sharedStyle.css];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 70
 * @framerIntrinsicWidth 316.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"iG0Gm77Mi":"partTop","aglOvVM2H":"partBottom"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerrfT5JQ1TT = withCSS(Component, css, "framer-j1Xqa");
export default FramerrfT5JQ1TT;
FramerrfT5JQ1TT.displayName = "Hero smallslogan";
FramerrfT5JQ1TT.defaultProps = {
    height: 70,
    width: 316.5
};
addPropertyControls(FramerrfT5JQ1TT, {
    iG0Gm77Mi: {
        defaultValue: "Part top",
        displayTextArea: false,
        title: "Part top",
        type: ControlType.String
    },
    aglOvVM2H: {
        defaultValue: "Part bottom",
        description: "Write your slogan",
        displayTextArea: false,
        title: "Part bottom",
        type: ControlType.String
    }
});
addFonts(FramerrfT5JQ1TT, [{
    explicitInter: true,
    fonts: [{
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
        url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
        url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+1F00-1FFF",
        url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0370-03FF",
        url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
        url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
        url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
        weight: "400"
    }, {
        family: "Inter",
        source: "framer",
        style: "normal",
        unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
        url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
        weight: "400"
    }]
}, ...getFontsFromSharedStyle(sharedStyle.fonts)], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerrfT5JQ1TT",
            "slots": [],
            "annotations": {
                "framerComponentViewportWidth": "true",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"auto\"]}}}",
                "framerVariables": "{\"iG0Gm77Mi\":\"partTop\",\"aglOvVM2H\":\"partBottom\"}",
                "framerIntrinsicHeight": "70",
                "framerIntrinsicWidth": "316.5",
                "framerImmutableVariables": "true",
                "framerColorSyntax": "true",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./rfT5JQ1TT.map