// Generated by Framer (4f3879e)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "3dkhxr", mediaQuery: "(min-width: 1200px)"}, {hash: "j7nq0w", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1xv6slt", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-etQFk", title: "Housemood | Privacy", viewport: "width=device-width"}
}

export const metadataVersion = 1